life/game/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter

from game.ApiViews.SimApi import SimApiView
from game.views import CreateSimView, GamesList, GameView

router = DefaultRouter()
router.register(r'sim-api', SimApiView)

urlpatterns = [
    url(r'games/new/$', CreateSimView.as_view(), name="create_sim"),
    url(r'games/$', GamesList.as_view(), name="games_list"),
    url(r'games/(?P<pk>[0-9]+)/$', GameView.as_view(), name='game'),
    url(r'', include(router.urls)),
]

life/life/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from game.views import UserMainMenuView

urlpatterns = [
    url(r'^$', UserMainMenuView.as_view(), name='user_main_menu'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^game/', include('game.urls', namespace='game')),
]

life/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

life/game/models.py
from datetime import datetime

from dateutil.relativedelta import relativedelta
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class Game(models.Model):
    user = models.ForeignKey(User,
                             blank=True,
                             null=True,
                             )
    sim = models.OneToOneField('Sim',)

    def __str__(self):
        return self.sim.__str__()


class Sim(models.Model):
    name = models.CharField(_('Name'),
                            max_length=255,
                            )
    surname = models.CharField(_('Surname'),
                               max_length=255,
                               )
    birthday_date = models.DateTimeField(_('Birthday date'),
                                         )
    satiety = models.PositiveSmallIntegerField(_('Satiety'),
                                               validators=[MinValueValidator(0),
                                                           MaxValueValidator(100)],
                                               default=100,
                                               )
    health = models.PositiveSmallIntegerField(_('Health'),
                                              validators=[MinValueValidator(0),
                                                          MaxValueValidator(100)],
                                              default=100,
                                              )
    thirst = models.PositiveSmallIntegerField(_('Thirsty'),
                                              validators=[MinValueValidator(0),
                                                          MaxValueValidator(100)],
                                              default=100,
                                              )
    happiness = models.PositiveSmallIntegerField(_('Happiness'),
                                                 validators=[MinValueValidator(0),
                                                             MaxValueValidator(100)],
                                                 default=100,
                                                 )
    account_balance = models.IntegerField(_('Account balance'),
                                          default=10000)

    def __str__(self):
        return f'{self.name} {self.surname}'

    @property
    def age(self):
        return relativedelta(datetime.today().date(), self.birthday_date.date()).years

life/game/forms.py
from datetime import datetime

from dateutil.relativedelta import relativedelta
from django import forms

from game.models import Sim


class CreateSimForm(forms.ModelForm):
    class Meta:
        model = Sim
        fields = ['name',
                  'surname',
                  'birthday_date',
                  'satiety',
                  'health',
                  'thirst',
                  'happiness',
                  'account_balance',
                  ]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['birthday_date'].widget = forms.HiddenInput()
        self.fields['satiety'].widget = forms.HiddenInput()
        self.fields['health'].widget = forms.HiddenInput()
        self.fields['thirst'].widget = forms.HiddenInput()
        self.fields['happiness'].widget = forms.HiddenInput()
        self.fields['account_balance'].widget = forms.HiddenInput()

        self.fields['birthday_date'].initial = datetime.now() - relativedelta(years=18)

life/game/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, ListView, DetailView

from game.forms import CreateSimForm
from game.models import Game


class UserMainMenuView(LoginRequiredMixin, TemplateView):
    template_name = 'game/user_main_menu.html'


class CreateSimView(LoginRequiredMixin, CreateView):
    template_name = 'game/create_sim.html'
    form_class = CreateSimForm

    def get_success_url(self):
        Game.objects.create(user=self.request.user, sim=self.object)
        return reverse_lazy("game:games_list")


class GamesList(LoginRequiredMixin, ListView):
    template_name = 'game/games_list.html'
    context_object_name = 'games_list'
    model = Game

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(user=self.request.user)


class GameView(LoginRequiredMixin, DetailView):
    template_name = 'game/game_main.html'
    context_object_name = 'game'
    model = Game

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['sim'] = self.object.sim
        return ctx

life/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
    {% block javascript %}{% endblock %}
</body>
</html>

life/templates/game/create_sim.html
{% extends 'base.html' %}

{% block title %}Create Sim{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Add Sim</button>
    </form>
{% endblock %}

life/templates/game/game_main.html
{% extends 'base.html' %}

{% block title %}{{sim.name}} {{sim.surname}}{% endblock %}

{% block content %}
    <p>{{ sim }} {{ sim.age }}</p>
    <p>Health: {{ sim.health }}</p>
    <p>Satiety: {{ sim.satiety }}</p>
    <p>Thirst: {{ sim.thirst }}</p>
    <p>Happiness: {{ sim.happiness }}</p>
    <p>Account balance: {{ sim.account_balance }}</p>

    <button onclick="sth()">Get age</button>
    <button onclick="sth2()">Increase thirst</button>

    {% block javascript %}
        <script>
            function sth() {
                $.get('{% url "game:sim-detail" sim.pk %}', function(data, status){
                    console.log("Data: " + data['age'] + "\nStatus: " + status);
                });
            }
            function sth2() {
                var tok = window.localStorage.getItem('token');
                $.ajax({
                    url: '{% url "game:sim-detail" sim.pk %}',
                    type: 'PUT',
                    data: {
                        name: 'awdgb',
                        surname: 'awdgb',
                        birthday_date: '2000-05-02 20:36:18.820774+00:00',
                        thirst: 90
                    },
                    beforeSend:function(xhr){
                        xhr.setRequestHeader("X-CSRFToken", $.cookie('csrftoken'));
                    },
                    dataType: 'json',
                    success: function(data) {
                        console.log('awdgb');
                    },
                    error:function(XMLHttpRequest, textStatus, errorThrown){
                       document.write(XMLHttpRequest.responseText);
                    }
                });
            }
        </script>
    {% endblock %}
{% endblock %}

life/templates/game/games_list.html
{% extends 'base.html' %}

{% block title %}Games List{% endblock %}

{% block content %}
    {% for game in games_list %}
        <p><a href="{% url 'game:game' game.id %}">{{ game }}</a></p>
    {% endfor %}
{% endblock %}

life/templates/game/user_main_menu.html
{% extends 'base.html' %}

{% block title %}Create Game Menu{% endblock %}

{% block content %}
    <a href="{% url 'game:games_list' %}" class="button">Load</a>
    <a href="{% url 'game:create_sim' %}" class="button">Create game</a>
{% endblock %}